# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-23 13:10+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:66
msgid "Archiving your home directory..."
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:96
msgid "Backup successful"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:96
msgid "Your home directory was successfully backed-up into"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:111
msgid "Backup failed"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:111
msgid "An error occurred during the backup:"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:131
msgid "Copying the backup file into your home directory..."
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:142
msgid "Extracting the content of the backup into your home directory..."
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:158
msgid "Cleaning up..."
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:164
msgid "Restoration successful"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:164
msgid "Your backup was successfully restored"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:180
msgid "Restoration failed"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:180
msgid "An error occurred while restoring the backup archive:"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:200
msgid "Opening the backup archive..."
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:226
msgid "Read error"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:226
msgid "An error occurred while opening the backup:"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:261
msgid "Excluded paths"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:262
msgid "Hidden paths"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:263
msgid "Exclude files"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:264
msgid "Exclude folders"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:265
msgid "Backup"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:268
msgid "Excluded Files and Directories"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:288
msgid "Included"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:292
msgid "Included hidden directories"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:356
msgid "Invalid path"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:356
msgid "is not located within your home directory. Not added."
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:387
msgid "<big><b>Load data into your home directory</b></big>"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:389
msgid "Restore your personal data from this backup"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:390
msgid "Overwrite existing files"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:391
msgid "Restore"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:392
msgid "View content"
msgstr ""
